name: Feature request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like Mucify to do?
      description: Describe the problem you want solved, not only the solution.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Anything you do today instead?
